// +build ignore

package uifont

import (
	"bytes"
	"fmt"
	"go/format"
	"io/ioutil"
	"log"
)

func main() {
	src, err := ioutil.ReadFile("Early Gameboy.ttf")
	if err != nil {
		log.Fatal(err)
	}

	b := new(bytes.Buffer)
	fmt.Fprintf(b, "// generated by go run gen.go; DO NOT EDIT\n")
	fmt.Fprintf(b, "package uifont\n\n")
	fmt.Fprintf(b, "var GBFONT = []byte{")
	for i, x := range src {
		if i&15 == 0 {
			b.WriteByte('\n')
		}
		fmt.Fprintf(b, "%#02x,", x)
	}
	fmt.Fprintf(b, "\n}\n")

	dst, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := ioutil.WriteFile("data.go", dst, 0666); err != nil {
		log.Fatal(err)
	}
}
